project:
  type: website

website:
  title: "Jacob Armitage"
  navbar:
    search: false
    left:
      - href: about.qmd
      - index.qmd
    right:
      - icon: github
        href: https://github.com/Kovshei
  page-footer:
    left: "Â© 2026 Jacob Armitage"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/jacob-armitage-5b2029158  
format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true

editor: visual

